name: Test

on:
  # Run on relevant pushes to select branches and on all relevant pull requests.
  push:
    branches:
      - main
      - trunk
      - 'release/**'
      - 'hotfix/[0-9]+.[0-9]+*'
      - 'feature/**'
    paths-ignore:
      - '**.css'
      - '**.js'
      - '**.md'
      - '**.png'
      - '**.txt'
      - '.babelrc'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'CHANGELOG'
      - 'LICENSE'
      - 'package.json'
      - '.phpcs.xml.dist'
      - 'phpcs.xml.dist'
      - 'yarn.lock'
      - '.github/dependabot.yml'
      - '.github/workflows/cs.yml'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/lint.yml'
      - 'config/**'
      - '!config/scripts/install-wp-tests.sh'
      - 'css/**'
      - 'js/**'
  pull_request:
    paths-ignore:
      - '**.css'
      - '**.js'
      - '**.md'
      - '**.png'
      - '**.txt'
      - '.babelrc'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'CHANGELOG'
      - 'LICENSE'
      - 'package.json'
      - '.phpcs.xml.dist'
      - 'phpcs.xml.dist'
      - 'yarn.lock'
      - '.github/dependabot.yml'
      - '.github/workflows/cs.yml'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/lint.yml'
      - 'config/**'
      - '!config/scripts/install-wp-tests.sh'
      - 'css/**'
      - 'js/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['7.3', '7.4', '8.0', '8.1', '8.2']
        coverage: [false]

        # Run code coverage only on high/low PHP.
        include:
        - php_version: 7.2
          coverage: true
        - php_version: 8.3
          coverage: true

    name: "Unit Test: PHP ${{ matrix.php_version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Run unit tests
        if: ${{ matrix.coverage == false }}
        run: composer test

      - name: Run the unit tests with code coverage
        if: ${{ matrix.coverage == true }}
        run: composer coverage

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage == true }}
        uses: coverallsapp/github-action@v2
        with:
          format: clover
          file: build/logs/clover.xml
          flag-name: php-${{ matrix.php_version }}
          parallel: true

  wp-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php_version: "7.2"
            wp_version: "6.2"
            multisite: true
            coverage: true

          - php_version: "7.3"
            wp_version: "trunk"
            multisite: true
            coverage: false

          - php_version: "7.4"
            wp_version: "latest"
            multisite: false
            coverage: false

          - php_version: "8.0"
            wp_version: "6.2"
            multisite: false
            coverage: false

          - php_version: "8.1"
            wp_version: "latest"
            multisite: true
            coverage: false

          - php_version: "8.2"
            wp_version: "6.3"
            multisite: true
            coverage: false

          # WP 6.4 is the earliest version which supports PHP 8.3.
          - php_version: '8.3'
            wp_version: '6.4'
            multisite: true
            coverage: true

    name: "WP Test: PHP ${{ matrix.php_version }} | WP ${{ matrix.wp_version }}${{ matrix.multisite == true && ' (+ ms)' || '' }}"

    # Allow builds to fail on as-of-yet unreleased WordPress versions.
    continue-on-error: ${{ matrix.wp_version == 'trunk' }}

    services:
      mysql:
        # Use MySQL 5.6 for PHP 7.2, use MySQL 5.7 for PHP 7.3 < 7.4, otherwise MySQL 8.0.
        # Also see: https://core.trac.wordpress.org/ticket/52496
        image: mysql:${{ ( matrix.php_version == '7.2' && '5.6' ) || ( matrix.php_version < '7.4' && '5.7' ) || '8.0' }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: ${{ matrix.coverage == true && 'xdebug' || 'none' }}

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-php-dependencies-with-composer
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install WP
        shell: bash
        run: config/scripts/install-wp-tests.sh wordpress_test root '' 127.0.0.1:3306 ${{ matrix.wp_version }}

      - name: Run WP tests - single site
        if: ${{ matrix.coverage == false }}
        run: composer test-wp

      - name: Run WP tests - multisite
        if: ${{ matrix.multisite == true && matrix.coverage == false }}
        run: composer test-wp
        env:
          WP_MULTISITE: 1

      - name: Run WP tests with code coverage - single site
        if: ${{ matrix.coverage == true }}
        run: composer coverage-wp

      - name: Run WP tests with code coverage - multisite
        if: ${{ matrix.multisite == true && matrix.coverage == true }}
        run: composer coverage-wp -- --coverage-clover build/logs/clover-wp-ms.xml
        env:
          WP_MULTISITE: 1

      - name: Upload coverage results to Coveralls
        if: ${{ success() && matrix.coverage == true }}
        uses: coverallsapp/github-action@v2
        with:
          format: clover
          file: build/logs/clover-wp.xml
          flag-name: php-${{ matrix.php_version }}-wp-${{ matrix.wp_version }}
          parallel: true

      - name: Upload coverage results to Coveralls - multisite
        if: ${{ success() && matrix.multisite == true && matrix.coverage == true }}
        uses: coverallsapp/github-action@v2
        with:
          format: clover
          file: build/logs/clover-wp-ms.xml
          flag-name: php-${{ matrix.php_version }}-wp-${{ matrix.wp_version }}-ms
          parallel: true

  coveralls-finish:
    needs: [unit-test, wp-test]
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
